DROP TABLE IF EXISTS empresas;
DROP TABLE IF EXISTS avaliacoes;

CREATE TABLE empresas (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nome TEXT NOT NULL,
    industria TEXT NOT NULL
);

CREATE TABLE avaliacoes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    data TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    avaliacao INTEGER NOT NULL,
    descricao TEXT NOT NULL,
    id_empresa INTEGER NOT NULL
);